materials = [
    "ping pong balls",
    "thumb tacks",
    "forks",
    "scissors",
    "bubble wrap",
    "sand paper",
    "keyboards/old electronics",
    "carboard",
    "zippers",
    "pens and pencils",
    "cans or bottles",
    "toothpicks",
    "toothbrushes",
    "felt",
    "paper clips",
    "mason jars",
    "styrofoam",
    "old newspaper/mail",
    "popsicle sticks",
    "pipe cleaners",
    "yarn",
    "duct tape",
    "fabric",
    "clay",
    "wire",
    "tissue paper",
    "recycled plastic",
    "toilet roll",
    "egg cartons"
]
