objects = [
    "a self portrait",
    "a phone case",
    "a light fixture",
    "an instrument",
    "a tote bag",
    "a shelf",
    "a cup",
    "a hat",
    "a chair",
    "glasses",
    "book ends",
    "a plate",
    "a bowl",
    "a shirt",
    "a stamp",
    "a spaceship",
    "a pencil holder",
    "a plant pot",
    "a keychain",
    "a frame",
    "a puzzle",
    "an organizer",
    "a doggy bag holder",
    "a plant watering device",
    "a game piece",
    "a grabber",
    "a sculpture",
    "a sign",
    "earrings"
]
